# supabase/config.toml

[functions.process-leave-approval]
enabled = true
verify_jwt = true
import_map = "./functions/process-leave-approval/deno.json"
entrypoint = "./functions/process-leave-approval/index.ts"

[functions.sync-tree-sales]
enabled = true
verify_jwt = true
import_map = "./functions/sync-tree-sales/deno.json"
entrypoint = "./functions/sync-tree-sales/index.ts"

[functions.push-sender]
enabled = true
# --- [수정] 이 값을 false로 변경하여 인증을 잠시 건너뜁니다. ---
verify_jwt = false 
import_map = "./functions/push-sender/import_map.json" 
entrypoint = "./functions/push-sender/index.ts"