
[functions.process-leave-approval]
enabled = true
verify_jwt = true
import_map = "./functions/process-leave-approval/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-leave-approval/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-leave-approval/*.html" ]
