name: Invoke Supabase Edge Function Hourly

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  invoke-function:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Function via cURL with DNS Retry
        run: |
          curl -i -X POST "${{ secrets.SUPABASE_FUNCTION_URL }}" \
            --dns-servers 8.8.8.8 \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"