name: Invoke Supabase Edge Function Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  invoke-function:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Function via cURL
        run: |
  curl -i -X POST "https://dzouudutnlgaolzlsfzb.supabase.co/functions/v1/sync-tree-sales" \
  -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
  -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
  -H "Content-Type: application/json"