name: Invoke Supabase Edge Function Hourly

on:
  schedule:
    - cron: '5 * * * *' # 매 시간 5분에 실행 (구글 시트 업데이트 지연 시간 고려)
  workflow_dispatch:

jobs:
  invoke-function:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Function
        uses: supabase/functions-action@v2 
        # API 방식이 아니므로 이제 curl이 아닌 원래의 Supabase Action을 사용해도 됩니다.
        with:
          project_id: ${{ secrets.SUPABASE_PROJECT_ID }}
          access_token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          function_name: sync-tree-sales```
